# Generated by Django 3.0.3 on 2020-02-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200225_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecaccountmodel',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
