# Generated by Django 3.0.3 on 2020-02-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200229_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemodel',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
